<?php 
if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
    $fet_prodcollection = $this->getBestsellerProduct();  
    $imagewidth = $this->getProductimagewidth();
    $imageheight = $this->getProductimageheight();
    $mode = 'grid';
    $title = __('Bestseller Products');
    $type = 'widget-bestsellers-grid';
    $image = 'bestseller_products_content_widget_grid';
}
?>

<?php if ($exist):

     // load  products by category id
//    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//    $cateinstance = $objectManager->create('Magento\Catalog\Model\CategoryFactory');
//    $cateid = 2;
//    // $allcategoryproduct = $objectManager->create('Magento\Catalog\Model\Product')->getCollection();
//     $allcategoryproduct = $cateinstance->create()->load($cateid)->getProductCollection()->addAttributeToSelect('*');
//    $product_ids = [];
//    foreach ($allcategoryproduct->getData() as $np_item) {
//
//        if($np_item['type_id'] == 'configurable'){
//            //parent product id
//            $parent_id = $np_item['entity_id'];
//            $childObj = $block->getConfigChildProductIds($parent_id);
//            foreach ($childObj as $child){
//               $getChildId[] = $child->getData();
//            }
//            //childrens
//            for ($i=0; $i < count($getChildId); $i++) {
//                $product_ids[] = $getChildId[$i]['entity_id'];
//            }
//        }
//    }

  
    $request_id = [];
    $iterator = 1;
    // checks if one of all products from best selled exists on selected category id
    foreach ($fet_prodcollection as $product):

        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $productModel = $objectManager->create('Magento\Catalog\Model\Product');
        $id = $product->getProductId();
        $_product = $productModel->load($product->getProductId());

        $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')
            ->setImageFile($_product->getFile())
            ->resize($imagewidth,$imageheight)
            ->getUrl();
        $codeModele = $_product->getData('code_modele');
        $productImageUrl2 = 'https://cdn-magento.maniet.be/photos/'.$codeModele.'/'.$codeModele.'_2d_0001_thumbnail.jpg';
        $array = get_headers($productImageUrl2);
        $string = $array[0];
        if(strpos($string,"200")) {
            $image_url = $productImageUrl2;
        } else {
            $productImageUrl2 = 'https://cdn-magento.maniet.be/photos/'.$codeModele.'/'.$codeModele.'_0001_thumbnail.jpg';
            $array = get_headers($productImageUrl2);
            $string = $array[0];
            if(strpos($string,"200")) {
                $image_url = $productImageUrl2;
            } else {
                $productImageUrl2 = 'https://cdn-magento.maniet.be/photos/'.$codeModele.'/'.$codeModele.'_2D_0001_thumbnail.jpg';
                $array = get_headers($productImageUrl2);
                $string = $array[0];
                if(strpos($string,"200")) {
                    $image_url = $productImageUrl2;
                }
            }
        }

    ?>
    <div class="bestseller-products">
        <div class="item-image">
            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                <a href="<?php /* @escapeNotVerified */ echo $this->_getProductUrl($id); ?>">
                    <img src="<?php echo $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                </a>
            </a>
        </div>
        <div class="item-details">
            <?php $optionId = $_product->getData('product_brand_controle'); ?>
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
            $select2 = "SELECT * FROM eav_attribute_option_value WHERE store_id = 0 AND option_ID = '".$optionId."'";
            $resultValues = $connection->fetchAll($select2);
            if(count($resultValues) > 0) {
                $brandId = $resultValues[0]['value'];
            } else {
                $brandId = '';
            }

            if($brandId != '') {
                $select3 = "SELECT * FROM pilotmag_brand_image WHERE code_marque = '".$brandId."'";
                $resultValues2 = $connection->fetchAll($select3);
                if(count($resultValues2) > 0) {
                    $imageName = $resultValues2[0]['image'];
                } else {
                    $imageName = '';
                }
            } else {
                $imageName = '';
            }


            //var_dump($resultValues2[0]['image']);
            ?>
            <?php $brandControle = $_product->getResource()->getAttribute('product_brand_controle')->getFrontend()->getValue($_product); ?>
            <?php
            $brandCode = $brandId;
            //$brandName = str_replace(' ','%20', strtolower($brandControle));
            $brandImage = 'https://cdn-magento.maniet.be/marques/'.$brandCode.'/'.$imageName;
            //var_dump($brandImage);
            $array = get_headers($brandImage);
            $string = $array[0];
            //var_dump($brandImage);
            if(strpos($string,"200")): ?>
                <!--<div class="brand-image">-->
                    <img src="<?php echo $brandImage ?>" alt="<?php echo $brandControle; ?>" class="brand-image"/>
                <!--</div>-->
            <?php endif; ?>
            <strong class="product-item-name">
                <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                   href="<?php /* @escapeNotVerified */ echo $this->_getProductUrl($id); ?>"
                   class="product-item-link">
                    <?php echo $block->escapeHtml($_product->getName()) ?>
                </a>
            </strong>
            <?php
                echo $this->getProductPriceHtml($_product, $type);
            ?>
        </div>
    </div>
    <?php
        endforeach;
        ?>
       
    <?php //endforeach ?>

<?php endif;?>
