<div class="footer-columns">
    <div>1</div>
    <div>1</div>
    <div>1</div>
    <div>1</div>
</div>  
<style type="text/css">
.footer-columns {
    box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    max-width: 1280px;
    padding-left: 20px;
    padding-right: 20px;
    width: auto;
    padding-top: 20px;
}

.footer-columns div{
    float: left;
    width: 300px;
    background: #ccc;
    /*margin: 0 0 0 10px;*/
}

@media (min-width: 768px), print
styles-l.css:2854
.footer-columns {
    border-top: none;
}
</style>