<div id="configmonkey_apikey" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"configmonkeyapikey":{
     "storeUrl": "<?php echo $this->getUrl('abandonedcart/stores/get');?>",
     "detailsUrl": "<?php //echo $this->getUrl('abandonedcart/ecommerce/getaccountdetails');?>",
     "storeGridUrl": "<?php echo $this->getUrl('abandonedcart/stores/index');?>"}}'>
</div>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="224px" style="padding-left: 15px;" height="60px" src="https://shop-website.s3.amazonaws.com/Logo_Ebizmarts.png"/><br><br>
        <div style="padding-left: 15px;">
            <p> <strong style="color:#EA7601;"><?php echo __('AbandonedCart v') ?><?php echo $this->getModuleVersion() ?><?php echo __(' by') ?></strong> <a target="_blank" href="http://shop.com"><strong>shop</strong></a></p>
            <p><?php echo __('Need help? See our ') ?><a href="http://wiki.shop.com/installation" target="_blank"><?php echo __('Wiki') ?></a><?php echo __(' or browse our ') ?><a href="http://shop.com/forums" target="_blank"><?php echo __('support forums') ?></a><?php echo __(' Got feedback? ') ?><a href="mailto:abandonedcart@shop-desk.zendesk.com?Subject=AbandonedCart For Magento Version <?php echo $this->getModuleVersion()?>"><?php echo __('Email us') ?></a></p>
            <p><?php echo __('You can find more extension in our ') ?><a href="http://store.shop.com" target="_blank"><?php echo __('Store') ?></a></p>
        </div>
    </h4>
</div>